public class checkoutParser{
	public cls_checkout checkout;
	public class cls_checkout {
		public String id;	//AxBOAO75cOkqO
		public String status;	//CANCELED
		public String created_at;	//2022-12-21T03:01:52.594Z
		public String updated_at;	//2022-12-21T03:06:53.589Z
		public String app_id;	//sq0idp-6RmOjVKT6UlxnjsIPZdN-w
		public String deadline_duration;	//PT5M
		public String cancel_reason;	//TIMED_OUT
		public String location_id;	//LCBN1N814BG2W
		public String payment_type;	//CARD_PRESENT
	    }
    }