/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class ClaimGetReqPayerStatusNightlyBatchTest {
  
@isTest
    public static void testDummy(){ 
        Test.startTest();
        
        XMLParserClass.dummyMethod();
         system.assertEquals(1,1);     
        Test.stopTest();
        
    }
    
}