public class CreateCardParser {
	public cls_card card;
	public cls_billing_address billing_address;
	public class cls_card {
		public String id;	//ccof:uIbfJXhXETSP197M3GB
		public String bin;	//411111
		public String card_brand;	//VISA
		public String card_type;	//CREDIT
		public String cardholder_name;	//Amelia Earhart
		public String customer_id;	//Q6VKKKGW8GWQNEYMDRMV01QMK8
		public boolean enabled;
		public String exp_month;	//11
		public String exp_year;	//2018
		public String last_4;	//1111
		public String prepaid_type;	//NOT_PREPAID
		public String reference_id;	//user-id-1
		public Integer version;	//1
	}
	Public class cls_billing_address {
		public String address_line_1;	//500 Electric Ave
		public String address_line_2;	//Suite 600
		public String locality;	//New York
		public String administrative_district_level_1;	//NY
		public String postal_code;	//10003
		public String country;	//US
	}
}