/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-16-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class ErrorController_Test 
{
	public static testMethod void errorTest()
    {
                Test.startTest();
        	         system.assertEquals(1, 1,'');	
        Test.stopTest();
    }
}