public class Payment_Parser{
	public cls_payment payment;
	public class cls_payment {
		public String id;	//R2B3Z8WMVt3EAmzYWLZvz7Y69EbZY
		public String created_at;	//2021-10-13T21:14:29.577Z
		public String updated_at;	//2021-10-13T21:14:30.504Z
		public String status;	//COMPLETED
		public String delay_duration;	//PT168H
		public String source_type;	//CARD
		public String location_id;	//L88917AVBK2S5
		public String order_id;	//pRsjRTgFWATl7so6DxdKBJa7ssbZY
		public String reference_id;	//123456
		public String note;	//Brief Description
		public String customer_id;	//W92WH6P11H4Z77CTET0RNTGFW8
		public String receipt_number;	//R2B3
		public String receipt_url;	//https://squareup.com/receipt/preview/EXAMPLE_RECEIPT_ID
		public String delay_action;	//CANCEL
		public String delayed_until;	//2021-10-20T21:14:29.577Z
		public String version_token;	//TPtNEOBOa6Qq6E3C3IjckSVOM6b3hMbfhjvTxHBQUsB6o
	}
}