public with sharing class StopRecursion {
    public static Boolean procedure = false;
    public static Boolean eraReceived = false;
    public static Map<Id,Boolean> isDenied = new Map<Id,Boolean>();
    public static Boolean stopLocationUpdation = true;
    public static Boolean isLeadConverted = false;
    public static Boolean opportunityUpdateForStage = false;
    public static Boolean accountUpdateForStage = false;
    public static Boolean deceasedStop = false;
    public static Boolean eventTimeZone = false;
    public static Boolean verifyDev = false;
    public static Boolean claimUpdate = true;
}